### ISSUE TITLE
Undefined Method error

### ISSUE THREAD

**Issue by JordanChoo** [kriansa/fuel-less#2]
I've installed the package recursivly and and configured the file on auto-load in my apps config file. Yet, I am getting the following error:

`ErrorException [ Error ]: Call to undefined method Less\Asset::instance()`

Do you have any insight into what is causing this problem and how it can be fixed?

**Comment by kriansa** [comment]
Did you installed the package inside PKGPATH/less ?

**Comment by JordanChoo** [comment]
Yeah, I called the git clone --recursive command and put all the files and folders into a folder called less in my packages path

**Comment by rpnzl** [comment]
Having the same error over here - package config, app config include, paths, etc. have been double-checked. My FuelPHP setup is not traditional, though, with my APP directory outside/above the FUEL directory that contains the core and packages.

**Comment by JordanChoo** [comment]
Has anyone managed to get it working?

**Comment by kriansa** [comment]
Sorry for the lack of support, i've been busy these days. I looked at the Fuel's asset class and looks like they changed it again... I don't know why yet, but i'm gonna fix this.

**Comment by kriansa** [comment]
Nope, looks like we both were getting the same error. The default branch of fuel's core is the 1.0, and it has the old Asset functionality. Please, change de branch of core to 1.1/develop and it works fine!

cd fuel/core
git checkout 1.1/develop

**Comment by JordanChoo** [comment]
Just tried it out and it's working perfectly! Thanks a ton (for both the support and the package) =)
