### ISSUE TITLE
undefined method error - 1.1/develop no longer an option?

### ISSUE THREAD

**Issue by ikmolbo** [kriansa/fuel-less#3]
Hi,

About the "ErrorException [ Error ]: Call to undefined method Less\Asset::instance()" error that you fixed by checking out the 1.1/develop branch of Fuel Core...

It seems that 1.1/develop is no longer available, and 1.2/master results in the error "Class 'Less\Fuel_Exception' not found". Is there any solution for this, or update to your (excellent) package on the way?

Thanks,

Matt

**Comment by kriansa** [comment]
Try 1.2/develop

**Comment by ikmolbo** [comment]
Thanks, but that just produces a different error - Class 'Fuel_Exception' not found (from PKGPATH/less/classes/asset/instance.php @ line 53)

Same error with 1.2/master.

**Comment by kriansa** [comment]
I just made a fix, update your branch and try again.

**Comment by ikmolbo** [comment]
Thanks - that worked.
