### ISSUE TITLE
Casset Support

### ISSUE THREAD

**Issue by dmyers** [kriansa/fuel-less#5]
What do you think of having Casset support? I was just wondering, I can work on it but don't want to unless you think it would be good too.

https://github.com/canton7/fuelphp-casset

Basically you can do something like:

``` php
// See if Casset package is used.
if (\Package::loaded('casset')) {
    return\Casset::css($css_file);
} else {
    return \Asset::css($css_file);
}
```

**Comment by kriansa** [comment]
I think that it would be more suitable create a casset branch with this feature. This extension is for Fuel Asset specific applications. If we do like you suggest, how could I know how its packages are made? Would we have to update this extension every time somebody create a new asset extension? This is odd...

Anyway, I still think that it's possible to merge the ideas from Casset and include support to Less.. What do you think? All I can think right now is to create a new branch with this new functionality.

**Comment by dmyers** [comment]
Let me know what you think of this:
https://github.com/dmyers/fuel-less/commit/9ad48040fb78a7b24aaf962e8cdca6b0fd4ba4e0

**Comment by kriansa** [comment]
I don't know exactly how casset works when handling with CSS scripts. I just read the README and looks like it minifies the JS/CSS scripts into one single file, won't less break that? Are you sure this is the best implementation for less in casset? When I created this package for Fuel, I meant to be simple and easy just like the original Asset::css. But doesn't mean that you have to use the same design in casset, I mean, Casset::css works just like the Fuel's Asset::css ? What about its group stuff? Will work as well? I'm sorry, but I don't know casset very well, and it looks more complicated than I thought. I need to get into the code to understand its workflow.

**Comment by dmyers** [comment]
I've been using it with your package for a while, but had to override the class to get it to work with Casset.

The way my stuff works is I call
Casset::less()
Which compiles the less into css, then Casset takes it and minfies and combines my assets into a new assets/cache folder and it just works.

**Comment by kriansa** [comment]
Very nice! 

But I'm still resisting to merge that into the master branch. Do you understand that it's an package for another package? It's not very pretty from my design point of view.

But still very useful and may help a lot of people, including me (when I drop Zend and get back with my sweet Fuel).

Can you send this pull request? I will make some tests and create a new branch for it.

And again, thanks for the contribuition! :)

**Comment by dmyers** [comment]
I was just revisiting this today and was curious if you got back into Fuel more lately?

I do understand your point about a package for a package, but I just thought it would be nice to support Fuel's Asset or Casset which are kind of both packages IMO.

I think the way I added it was just a Casset class which you can either use or not use if you don't have Casset no worries, and still works with Asset. Maybe check it out in the other issue.

No problems, glad to help. You made a great package. :)

**Comment by kriansa** [comment]
Hey Derek,

I'm sorry for the long delay. I've been busy since then, and I can't work on it the next weekend.
I have some plans for a new version for this package, making it more flexible, including:
- Abstraction of compile layer: You will be able to use lessphp or jsless, or anything that turns a less into css code - you'll just have to write a adapter for that;
- Turn it into a framework-agnostic package. You should use as a single library or as a framework package, doesn't matter which - again, you'll just have to write a simple file to adapt to your needs.
- Enable the support to watch files included by @include 

I hope that next week I find some time to work on it.

Thanks for helping!

**Comment by kriansa** [comment]
Just an update. Today I'll have some time to work on it. Hope I can finish all I wish to do.

**Comment by kriansa** [comment]
Hi @dmyers,

I've been working these days on this new 2.0 branch, hope this fit your needs, please, take a look.

https://github.com/kriansa/fuel-less/tree/2.0/master
