### ISSUE TITLE
Does it provide a cached css if no changes?

### ISSUE THREAD

**Issue by ghost** [kriansa/fuel-less#7]
Hello contributors!

Does you package provide a method to cache the CSS when not changed?

Thanks,
Allan. 

(Yes I know, there's low activity on that projet, but **never we know**)

**Comment by kriansa** [comment]
In production environment, it won't look for changes, so you must always commit your final css into you production branch (or whatever is your deploy procedure).

You may take a look here: https://github.com/kriansa/fuel-less/blob/2.0/master/classes/asset/instance.php#L78

**Comment by ghost** [comment]
This is a great method to work with, I like that.
Thanks for you time @kriansa :+1:
